Numpy

In [3]:
import numpy as np


In [4]:
dataset = np.genfromtxt('data/StudentsPerformance.csv', delimiter=',', skip_header=1, dtype=int)

In [5]:
dataset

array([[-1, -1, -1, ..., 69, 90, 88],
       [-1, -1, -1, ..., 90, 95, 93],
       [-1, -1, -1, ..., 47, 57, 44],
       ...,
       [-1, -1, -1, ..., 59, 71, 65],
       [-1, -1, -1, ..., 68, 78, 77],
       [-1, -1, -1, ..., 77, 86, 86]])

filtros datos


In [6]:
print(dataset.ndim)
print(dataset.shape)


2
(999, 8)


In [7]:
write_scores = dataset[:, -1]
read_scores = dataset[:, -2]
math_scores = dataset[:, -3]

In [8]:
math_scores.shape

(999,)

## Operaciones aritméticas

sumatorio de notas

In [9]:
scores = write_scores + read_scores + math_scores
scores[:20]

array([247, 278, 148, 229, 232, 275, 122, 195, 148, 164, 135, 219, 220,
       161, 222, 263,  78, 134, 173, 198])

In [10]:
scores.shape

(999,)

## nota media

In [11]:
final_scores = scores / 3
final_scores = np.round(final_scores,0)
final_scores[:20]

array([82., 93., 49., 76., 77., 92., 41., 65., 49., 55., 45., 73., 73.,
       54., 74., 88., 26., 45., 58., 66.])

In [12]:
final_scores.dtype

dtype('float64')

In [13]:
final_scores = final_scores.astype(int)
final_scores[:20]

array([82, 93, 49, 76, 77, 92, 41, 65, 49, 55, 45, 73, 73, 54, 74, 88, 26,
       45, 58, 66])

## Ordenar

In [14]:
final_scores_asc = np.sort(final_scores)
print(f"Nota mas baja: {final_scores_asc[0]}")
print(f"Nota mas alta: {final_scores_asc[0]}")

Nota mas baja: 9
Nota mas alta: 9


### Filtrar datos

In [15]:
success_scores = final_scores[final_scores >= 50]
fail_scores = final_scores[final_scores < 50]

In [16]:
print(f"success: {success_scores.shape}")
print(f"fail:{fail_scores.shape}")

success: (899,)
fail:(100,)


In [17]:
fail_index = np.where (final_scores < 50)
fail_index

(array([  2,   6,   8,  10,  16,  17,  32,  51,  54,  58,  60,  65,  71,
         73,  74,  75,  79,  80,  83,  90,  92, 130, 135, 142, 144, 173,
        181, 183, 187, 203, 210, 216, 230, 249, 261, 264, 279, 280, 283,
        295, 297, 306, 323, 326, 328, 330, 336, 337, 362, 374, 382, 383,
        394, 400, 423, 447, 454, 465, 526, 527, 551, 553, 554, 563, 564,
        574, 595, 600, 615, 639, 682, 705, 722, 723, 728, 730, 732, 776,
        784, 786, 793, 806, 809, 810, 839, 841, 857, 861, 866, 882, 888,
        894, 895, 901, 909, 920, 927, 977, 979, 987], dtype=int64),)

In [18]:
final_scores[fail_index]

array([49, 41, 49, 45, 26, 45, 40, 46, 39,  9, 37, 40, 47, 46, 41, 26, 49,
       46, 38, 32, 46, 43, 49, 49, 31, 49, 49, 49, 48, 47, 30, 38, 44, 48,
       48, 47, 49, 46, 43, 43, 45, 49, 43, 23, 49, 40, 48, 30, 31, 43, 44,
       41, 45, 46, 38, 45, 47, 32, 44, 39, 46, 46, 35, 48, 45, 49, 23, 29,
       40, 48, 38, 39, 47, 44, 43, 48, 49, 41, 42, 30, 48, 42, 39, 47, 46,
       34, 49, 40, 48, 48, 48, 35, 31, 41, 47, 45, 44, 48, 18, 45])

### Estadísticas

In [19]:
np.mean(final_scores[fail_index])

41.82

In [20]:
np.mean(success_scores)

70.64182424916574

Cargar todas las columnas del dataset csv en arrays distintos

big_arrays

In [22]:
big_array = np.random.rand(100000)

In [23]:
big_array = np.random.rand(1000000000)

In [1]:
suma = 0
for score in big_array:
    suma += score
print (suma)

NameError: name 'big_array' is not defined