## Numpy

In [151]:
# !pip install numpy

In [152]:
import numpy as np


In [153]:
np.__version__

'1.24.3'

1.Crear arrays

np.array

In [154]:
numbers =[1, 2, 3, 4]
numbers

[1, 2, 3, 4]

In [155]:
arr=np.array([1, 4, 2, 5, 3])
arr

array([1, 4, 2, 5, 3])

In [156]:
type(arr)

numpy.ndarray

In [157]:
np.array([3, 14, 4, 2, 3])

array([ 3, 14,  4,  2,  3])

In [158]:
numbers_tuple = (1,2,3)
numbers_list = list(numbers_tuple)
numbers

[1, 2, 3, 4]

In [159]:
type(numbers)

list

In [160]:
np.array([1,2])

array([1, 2])

In [161]:
np.array([1, 2, 3, 4], dtype='float16')

array([1., 2., 3., 4.], dtype=float16)

## np.zeros

In [162]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## np.ones

In [163]:
np.ones((3, 5), dtype= float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## np.full

In [164]:
np.full((3,5), 15)

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

## np.arange

In [165]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [166]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [167]:
np.arange(5, 20,3)

array([ 5,  8, 11, 14, 17])

In [168]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

np.linspace

##### devuelve números espaciados uniformemente en un intervalo especifico.

In [169]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

np.random

In [170]:
np.random.random((3, 3))

array([[0.77834548, 0.94957105, 0.66252687],
       [0.01357164, 0.6228461 , 0.67365963],
       [0.971945  , 0.87819347, 0.50962438]])

In [171]:
np.random.randint(0, 10, (3, 3))

array([[0, 7, 5],
       [9, 0, 2],
       [7, 2, 9]])

In [172]:
np.random.normal(0, 1, (3, 3))

array([[-0.81314628, -1.7262826 ,  0.17742614],
       [-0.40178094, -1.63019835,  0.46278226],
       [-0.90729836,  0.0519454 ,  0.72909056]])

In [173]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

np.empty

In [174]:
arr1 = np.empty(6)
arr1.ndim

1

## 2.Atributos de arrays

In [175]:
np.random.seed(0)

In [176]:
x1=np.random.randint(10, size=6) #unidimensional array
x1

array([5, 0, 3, 3, 7, 9])

In [177]:
x2 = np.random.randint(10, size=(3,4)) #bidimensoional array
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [178]:
x3=np.random.randint(10,size=(3, 4, 5)) #tridimensionalñ array
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [179]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [180]:
print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size:", x2.size)
print("dtype:", x2.dtype)
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

x2 ndim: 2
x2 shape: (3, 4)
x2 size: 12
dtype: int32
itemsize: 4 bytes
nbytes: 48 bytes


In [181]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [182]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


## 3.Acceder a los elementos:

## indexados

In [183]:
x1

array([5, 0, 3, 3, 7, 9])

In [184]:
print(x1[0])
print(x1[1])
print(x1[2])

5
0
3


In [185]:
print(x1[-1])
print(x1[-2])
print(x1[-3])

9
7
3


In [186]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [187]:
print(x2[0,0])
print(x2[0,1])
print(x2[0,2])
print(x2[0,3])
print(x2[1,0])
print(x2[1,1])
print(x2[1,2])
print(x2[1,3])
print(x2[2,0])
print(x2[2,1])
print(x2[2,2])

3
5
2
4
7
6
8
8
1
6
7


In [188]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [189]:
x3[0,0,0]

8

In [190]:
x2[0][0]

3

In [191]:
print(x2[0-1])

[1 6 7 7]


In [192]:
print(x2[0,-1])

4


In [193]:
x2.dtype

dtype('int32')

In [194]:
print("valor original:", x2[0,0])
x2[0,0] = 8.9
print("valor modificado:", x2[0.0])

valor original: 3


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

## 4.Acceder a subarrays: slicing

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[::2] # start, stop, step

array([0, 2, 4, 6, 8])

In [ ]:
print(x[:5]) #start, stop, step
print(x[5:])
print(x[3:7])

[0 1 2 3 4]
[5 6 7 8 9]
[3 4 5 6]


In [ ]:
print(x[::2])
print(x[1::2])
print(x[::-1])

[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


In [ ]:
x2

array([[8, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[:2, 1:3]

array([[5, 2],
       [6, 8]])

In [ ]:
x2[:2, ::2]

array([[8, 2],
       [7, 8]])

In [ ]:
print(x2[:, 0])
print(x2[0,:])

[8 7 1]
[8 5 2 4]


## 5.Copy vs. view

#### las operaciones slicing devuelven vistas no copias. significa que si cambian datos en el array original también se cambian en la vista.

In [ ]:
x2= np.random.randint(10, size=(3,4)) # bidimensional
x2

array([[4, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1]])

In [ ]:
x2_sub = x2[:2, :2] #tecnica slicing
x2_sub

array([[4, 3],
       [8, 4]])

In [ ]:
print(x2)
print('\n')
print(x2_sub)

[[4 3 4 4]
 [8 4 3 7]
 [5 5 0 1]]


[[4 3]
 [8 4]]


In [ ]:
x2_sub_copy = x2[:2, :2].copy() #método copy() para crear una copia

In [ ]:
x2_sub_copy[0, 0] = 50

In [ ]:
print(x2)
print('\n')
print(x2_sub_copy)

[[4 3 4 4]
 [8 4 3 7]
 [5 5 0 1]]


[[50  3]
 [ 8  4]]


## 6.Redimensionar un array (reshape)

##### (reshape)

In [ ]:
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [ ]:
x.ndim

1

In [ ]:
x.shape

(9,)

In [ ]:
type(x.shape)

tuple

In [ ]:
x_2d = x.reshape ((3, 3))
print(x_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x_2d.ndim

2

In [ ]:
print(x.reshape((1, 9))) # 2 dimensiones 1 fila y 9 columnas

[[1 2 3 4 5 6 7 8 9]]


In [195]:
x.reshape((1, 9)).ndim

2

np.newaxis

In [197]:
printx(x); print(x.ndim); print(x.shape)

NameError: name 'printx' is not defined

In [198]:
y = x[np.newaxis, :]; print(y); print(y.ndim); print(y.shape)

[[1 2 3 4 5 6 7 8 9]]
2
(1, 9)


In [199]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [200]:
arr.shape

(4,)

In [201]:
row_vec = arr[np.newaxis]
row_vec

array([[0, 1, 2, 3]])

In [202]:
row_vec.shape

(1, 4)

In [203]:
col_vec = arr[:, np.newaxis]
col_vec

array([[0],
       [1],
       [2],
       [3]])

In [204]:
col_vec.shape

(4, 1)

In [205]:
arr[np.newaxis, np.newaxis, :]

array([[[0, 1, 2, 3]]])

In [206]:
arr[:, np.newaxis, np.newaxis]

array([[[0]],

       [[1]],

       [[2]],

       [[3]]])

## ravel

In [207]:
x = np. array([1, 2, 3, 4, 5])
print(x); print(np,ravel(x))

[1 2 3 4 5]


NameError: name 'ravel' is not defined

In [209]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.ndim)

[[1 2 3]
 [4 5 6]]
2


In [210]:
print(np.ravel(x))
print(np.ravel(x).ndim)

[1 2 3 4 5 6]
1


### 7.Concatenar arrays

Concatenate

In [211]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = [99, 99, 99]

print(x); print(y); print(z); print('\n')

print(np.concatenate([x, y]))
print(np.concatenate([x,y,z]))
print(x)

[1 2 3]
[4 5 6]
[99, 99, 99]


[1 2 3 4 5 6]
[ 1  2  3  4  5  6 99 99 99]
[1 2 3]


In [214]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [215]:
print("shape", grid.shape); print("dimensiones", grid.ndim)

shape (2, 3)
dimensiones 2


In [216]:
y = np.concatenate([grid, grid])
print(y); print(y.ndim); print (y.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
2
(4, 3)


In [217]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

vstack

In [218]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [219]:
grid = np.array([[9, 8, 7], [6, 5, 4]])
grid

array([[9, 8, 7],
       [6, 5, 4]])

###### # Da error porque x tiene 1 dimensión y grid tiene 2 dimensiones
###### # np.concatenate([x, grid], axis= 0)

In [220]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

hstack

###### # Da error porque x tiene 1 dimensión y grid tiene 2 dimensiones
###### # np.hstack([x, grid])


In [221]:
y = np.array([4, 5, 6])
np.hstack([x, y])

array([1, 2, 3, 4, 5, 6])

In [222]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [224]:
y = np.array([[99], [99]])
y

array([[99],
       [99]])

In [225]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [226]:
y = np.array([4, 5])
y

array([4, 5])

In [228]:
y = y.reshape(2, 1)
y

array([[4],
       [5]])

In [229]:
np.hstack([grid, y])

array([[9, 8, 7, 4],
       [6, 5, 4, 5]])

## 8.separar arrays (split)

In [230]:
x= [1, 2, 3, 99, 99, 3, 2, 1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [233]:
x1, x2, x3 = np.split(x, [3,5])
print(x1)
print(x2)
print(x3)

[1 2 3]
[99 99]
[3 2 1]


vsplit()

In [234]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [235]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [236]:
upper, lower = np.vsplit(grid,[1])
print(upper)
print('\n')
print(lower)

[[0 1 2 3]]


[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [237]:
left, right = np.hsplit(grid,[3])
print(left)
print('\n')
print(right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


[[ 3]
 [ 7]
 [11]
 [15]]


## Operaciones sobre arrays

aritméticas

In [ ]:
# lista de python
# numbers = [1,2,3]
# numbers + 2 # TypeError: can only concatenate list (not "int") to list


In [238]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [239]:
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("x ** 2 =", x ** 2)
print("-x = ", -x)
print("x % 2 = ", x % 2)

x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
x ** 2 = [0 1 4 9]
-x =  [ 0 -1 -2 -3]
x % 2 =  [0 1 0 1]


In [240]:
-(0.5*x + 1) ** 2


array([-1.  , -2.25, -4.  , -6.25])

In [241]:
print(np.arange(5))
print(np.arange(1,6))

[0 1 2 3 4]
[1 2 3 4 5]


In [242]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [243]:
np.arange(5) // np.arange(1, 6)  # División suelo elimina la parte decimal

array([0, 0, 0, 0, 0])

In [244]:
np.arange(5) // np.arange(1, 6)  # División suelo elimina la parte decimal

array([0, 0, 0, 0, 0])

In [245]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [246]:
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [247]:
x ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [248]:
x = np.array([-2, -1, 0, 1, 2])
x

array([-2, -1,  0,  1,  2])

In [249]:
np.absolute(x)  # ``np.abs`` is a shorthand for this function.

array([2, 1, 0, 1, 2])

In [250]:
np.abs(x) 

array([2, 1, 0, 1, 2])

In [251]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [252]:
print("theta      =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tag(theta) =", np.tan(theta))

theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tag(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [253]:
x = [-1, 0, 1]

In [254]:
print("arcsin(x) =", np.arcsin(x))
print("arccos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))

arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


exponenciales y logarítmicas

In [255]:
x = [1, 2, 3]
x

[1, 2, 3]

In [256]:
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("4^x   =", np.power(4, x))

e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
4^x   = [ 4 16 64]


In [257]:
x = [1, 2, 4, 10]
x

[1, 2, 4, 10]

In [258]:
print("ln(x)   =", np.log(x))
print("ln2(x)   =", np.log2(x))
print("ln10(x)   =", np.log10(x))

ln(x)   = [0.         0.69314718 1.38629436 2.30258509]
ln2(x)   = [0.         1.         2.         3.32192809]
ln10(x)   = [0.         0.30103    0.60205999 1.        ]


In [259]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [260]:
y = np.empty(5) 
np.multiply(x, 10, out=y)

array([ 0., 10., 20., 30., 40.])

In [261]:
y

array([ 0., 10., 20., 30., 40.])

reduce

In [263]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

In [264]:
x + 5

array([ 6,  7,  8,  9, 10])

In [265]:
np.add(x,5)

array([ 6,  7,  8,  9, 10])

In [266]:
cont = 0
for i in x:
    cont += i; print(cont)

1
3
6
10
15


In [267]:
np.add.reduce(x)  # lo mismo que lo anterior pero más óptimo

15

In [268]:
np.multiply.reduce(x)

120

accumulate

In [269]:
x

array([1, 2, 3, 4, 5])

In [270]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [271]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

outer()

In [272]:
print(x)

[1 2 3 4 5]


In [273]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

min(), max(), sum()

In [274]:
big_array = np.random.rand(10000)

In [275]:
# descomentar para evaluar, puede tardar un poco en ejecutar
# %timeit sum(big_array)
# %timeit np.sum(big_array)

In [ ]:
np.min(big_array)

In [276]:
np.max(big_array)


0.9999709462497284

In [277]:
matrix = np.random.random((3, 4))
matrix

array([[0.75788483, 0.88526439, 0.51827654, 0.53466419],
       [0.43881854, 0.53992505, 0.02883074, 0.58066779],
       [0.64229993, 0.99807934, 0.27720631, 0.92986366]])

In [278]:
matrix.sum()

7.131781310411769

In [279]:
matrix.min()

0.02883074189769108

In [280]:
matrix.min(axis=0)

array([0.43881854, 0.53992505, 0.02883074, 0.53466419])

In [281]:
matrix.min(axis=0)

array([0.43881854, 0.53992505, 0.02883074, 0.53466419])

In [284]:
matrix.min(axis=1)

array([0.51827654, 0.02883074, 0.27720631])

Ejemplo

In [283]:
# !pip install pandas

In [285]:
import pandas as pd
df = pd.read_csv('../data/president_heights.csv')
df.head()

ModuleNotFoundError: No module named 'pandas'

In [3]:
print(np.percentile(match_scores,25))



NameError: name 'np' is not defined

In [ ]:
print(np.percentile(match_scores,25))

NameError: name 'np' is not defined

In [4]:
top_10 = match_scores >= np.percentile (match_scores, 90)ç
math_top_10 = math_scores[top_10]

SyntaxError: invalid syntax (1995550021.py, line 1)